# Generated by Django 2.2.7 on 2019-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
    ]
